import React from 'react'

export default function Home() {
  return (
    <div>
      <h1>HOme page</h1>
      <p style={{ fontSize: "1.5em", fontFamily: "bold" }}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque eius provident explicabo ea? Iusto labore mollitia, atque voluptatem perspiciatis nostrum, beatae odit odio, enim ut doloremque! Quaerat eos cupiditate sunt delectus quas at est eum, corrupti nemo quasi molestias nisi, eaque nihil nam neque praesentium recusandae natus quam rem dolore officiis repudiandae harum illo similique. Illum tempore commodi natus dolor, nostrum quasi. Voluptate laborum odit labore similique est quia corrupti maxime beatae tempore rem delectus architecto voluptas fuga eaque numquam, dolor, dolorum sit repellat error nulla aut dicta ab possimus totam? Dolores, et, eius quod voluptatum illo culpa qui aliquid commodi architecto, molestias aperiam delectus nostrum cum. Explicabo nulla eaque dolorum placeat aut consectetur deserunt, vel aliquam? Sint nam saepe magni commodi ullam, voluptates beatae, corrupti rerum earum corporis, consequuntur maxime inventore repudiandae nulla ad? Rem omnis modi repudiandae iste, similique earum facere minus itaque delectus nesciunt vitae enim fugit beatae odio facilis recusandae quidem dicta. Labore, quibusdam, nostrum explicabo animi incidunt inventore nam reiciendis voluptate alias tempora rerum maiores aperiam a? Sequi, quas vero hic temporibus, accusamus illo nulla tenetur totam quia quo officia quaerat perspiciatis recusandae atque magni, quae earum dicta. Ipsum illo molestias fuga expedita doloribus facere. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis officia ullam commodi aliquam nam. Fugiat, repudiandae adipisci illum mollitia iste perspiciatis ullam alias veritatis quae architecto pariatur! Accusantium saepe optio iusto assumenda, totam cum ipsum velit temporibus, nesciunt aspernatur perspiciatis! Earum veniam dolorem excepturi at pariatur, iusto ipsum mollitia quas? Nulla beatae quis hic odio unde corrupti aspernatur labore, ducimus possimus omnis illo repellendus esse nesciunt cupiditate dolorem voluptate consectetur? Tenetur beatae doloremque repellendus illo ipsam excepturi eos, ipsa sapiente exercitationem quibusdam? Voluptas nesciunt amet voluptatum asperiores, quas cupiditate officia aliquid natus distinctio nulla, a labore, pariatur excepturi saepe! Facilis!
      </p>
    </div>)
}
